### ISSUE TITLE
Colon support

### ISSUE THREAD

**Issue by NewAbbreviations950** [Imel23/TM1637-Library-for-Raspberry-Pi-Pico#1]
Hi, would you possibly be able to add support for the colon for time based projects. I could possibly hack it in but I'm just learning C and it wouldn't be pretty.
This library is great btw, thank you!

**Comment by Imel23** [comment]
> Hi, would you possibly be able to add support for the colon for time based projects. I could possibly hack it in but I'm just learning C and it wouldn't be pretty.
> 
> This library is great btw, thank you!

Thank you for your kind words! I’m glad you’re enjoying the library. I’ll work on adding support for the colon for time-based projects very soon. Stay tuned!

**Comment by NewAbbreviations950** [comment]
Thanks so much, I'm looking forward to it!
